### ISSUE TITLE
NETCDF 1.6.0 Breaking Tests

### ISSUE THREAD

**Issue by ssolson** [MHKiT-Software/MHKiT-Python#177]
The latest version of NETCDF has breaking changes for MHKiT's tests during the installation process of the tests.

As an immediate fix, I will require the previous version of NetCDF in the Develop branch to complete the current PR to update the Development to the master branch for PR #176.

I will follow up on the error below in a future PR.

```
Downloading netCDF4-1.6.0.tar.gz (774 kB)
     -------------------------------------- 774.2/774.2 kB 8.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  python setup.py egg_info did not run successfully.
  exit code: 1
  [29 lines of output]
  reading from setup.cfg...
      HDF5_DIR environment variable not set, checking some standard locations ..
  checking C:\Miniconda\envs\test\include ...
  hdf5 headers not found in C:\Miniconda\envs\test\include
  checking C:\Miniconda\envs\test\Library\include ...
  hdf5 headers not found in C:\Miniconda\envs\test\Library\include
  checking C:\Users\runneradmin\include ...
  hdf5 headers not found in C:\Users\runneradmin\include
  checking /usr/local\include ...
  hdf5 headers not found in /usr/local\include
  checking /sw\include ...
  hdf5 headers not found in /sw\include
  checking /opt\include ...
  hdf5 headers not found in /opt\include
  checking /opt/local\include ...
  hdf5 headers not found in /opt/local\include
  checking /opt/homebrew\include ...
  hdf5 headers not found in /opt/homebrew\include
  checking /usr\include ...
  hdf5 headers not found in /usr\include
  Traceback (most recent call last):
    File "<string>", line 36, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-1ff035lt\netcdf4_b33f62e6324c4054b6b47aa5a10d45a5\setup.py", line 444, in <module>
      _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
    File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-install-1ff035lt\netcdf4_b33f62e6324c4054b6b47aa5a10d45a5\setup.py", line 385, in _populate_hdf5_info
Error:       raise ValueError('did not find HDF5 headers')
  ValueError: did not find HDF5 headers
  [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
Encountered error while generating package metadata.
See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Process completed with exit code 1.
```

**Comment by ssolson** [comment]
Fixed in  #1941

Additoinal package checks are now occuring in #240
